### ISSUE TITLE
pseudonetcdf installation

### ISSUE THREAD

**Issue by eathana** [barronh/pseudonetcdf#11]
Hello,
I think I have (almost) successfully installed the software in a linux machine, following the instructions https://github.com/barronh/pseudonetcdf/wiki/Install-Instructions (paragraph 4), EXPECT FOR instruction g. pip install --no-deps --upgrade --install-option="--prefix=${PWD}/miniconda/" git+https://code.google.com/p/pseudonetcdf/

which failed: Error [Errno 2] No such file or directory while executing command git clone -q https://code.google.com/p/pseudonetcdf/ /tmp/pip-YfkOpm-build
Cannot find command 'git'
Do you have any solution on this? 

Consequently, is this the (only) reason that, when executing the command "pncdump -f uamiv CAMx.*.avrg.grd02 test.nc", the command is not found in the machine? Btw, is this the correct command to translate the camx binary outputs to netcdf files, so that they are then plotted with panoply?

Thank you in advance

**Comment by barronh** [comment]
1) if you don't have git, you can either install git or download the zip file and modify the pip command to point to the local file. 

2) You can download the zip from the github.com/barronh/pseudonetcdf page. 

3) If you do install git you'll have to update the URL. The instructions you used need to be updated to reflect the move from googlecode to github. Use the pip command at the bottom of the page at github.com/barronh/pseudonetcdf

**Comment by eathana** [comment]
thank you, i have now plotted my results!
