### ISSUE TITLE
Convert CMAQ output from IOAPI to WRF output NC file

### ISSUE THREAD

**Issue by ChrisTang19** [barronh/pseudonetcdf#110]
Hello @barronh

I want to convert CMAQ output from IOAPI to WRF output format NC file.
I notice your website, may I ask to tell me, by which command or sofware i can change it?

So appreciate.

Regards,
Chris

**Comment by barronh** [comment]
Thanks for the query. I have started a repo for examples that is separate. See the cmaq2wrf example in https://github.com/barronh/pseudonetcdf_examples. I had an example where I used an existing WRF file and just modified the metadata. However, I thought it would be more useful to have a truly independent example. I believe the example currently supports Lambert Conformal and Polar stereographic.  Let me know if the example is helpful, or if it needs to be updated in any way.

**Comment by barronh** [comment]
Since I haven't heard anything back, I am going to close this issue.
