### ISSUE TITLE
windrose

### ISSUE THREAD

**Issue by zfarooqui** [barronh/pseudonetcdf#113]
HI Barron,

I created pollution rose script using windrose from Pseudonetcdf and found that windrose is not classifying the bins correctly. 

Note: args.fromnorth

https://github.com/barronh/pseudonetcdf/blob/master/scripts/pncwindrose.py
Line 42: 
thetas = ((np.radians((wd) // width * width)).astype('f') %

needs to be 

thetas = ((np.radians((wd + halfwidth) // width * width)).astype('f') %

I request you to please take out some time and look into the issues. If you need data/binning/plot I created then I can provide.

Thank you,

**Comment by barronh** [comment]
Thanks for posting this. Sorry it is taking so long for me to update.

**Comment by barronh** [comment]
Addressed in main. I have quit using the scripts all-together, so this fell off my radar. Sorry @zfarooqui
