### ISSUE TITLE
pending deprecations

### ISSUE THREAD

**Issue by mathause** [barronh/pseudonetcdf#115]
in xarray we get some deprecation warnings that stem from pseudonetcdf.

- `"rU"` read mode: 

```python-traceback
 /usr/share/miniconda/envs/xarray-tests/lib/python3.8/site-packages/PseudoNetCDF/icarttfiles/ffi1001.py:95:
DeprecationWarning: 'U' mode is deprecated
    f = openf(path, 'rU', encoding=encoding)
```
there are several uses of `"rU"` those, e.g.:

https://github.com/barronh/pseudonetcdf/blob/ddfa0c4bed7f2f320ce3b68aaffa979572ea60ff/src/PseudoNetCDF/icarttfiles/ffi1001.py#L65-L66

The suggestion seems to be to just use `"r"` (https://stackoverflow.com/questions/56791545/what-is-the-non-deprecated-version-of-open-u-mode)

* Time tuple will be replaced by datetime and dateutil
```python-traceback
../../../../../usr/share/miniconda/envs/xarray-tests/lib/python3.8/site-packages/PseudoNetCDF/camxfiles/timetuple.py:18
  /usr/share/miniconda/envs/xarray-tests/lib/python3.8/site-packages/PseudoNetCDF/camxfiles/timetuple.py:18: PendingDeprecationWarning: Time tuple will be replaced by datetime and dateutil
    warn(PendingDeprecationWarning(
```

I don't think it's urgent, just wanted to mention it here. xref  pydata/xarray#3266

**Comment by barronh** [comment]
Thanks for the heads up! I'll fix these.

**Comment by barronh** [comment]
The rU has been changed to r in PR #116. timetuple should still be addressed.
