### ISSUE TITLE
add __version__ to PseudoNETCDF

### ISSUE THREAD

**Issue by mathause** [barronh/pseudonetcdf#128]
PseudoNETCDF currently does not have the conventional `PseudoNetCDF.__version__` string. Would nice if this was added. It currently needs to be imported as:

```python
from PseudoNetCDF import version

version.version
```

In addition, when installing pseudonetcdf with conda the version is also reported wrong - it reports `'3.1.0.dev0+Unknown'` (I am not sure if that has to be fixed here or in [conda-forge/pseudonetcdf-feedstock](https://github.com/conda-forge/pseudonetcdf-feedstock).

The background is that the new release breaks an xarray test. This should be easily fixable but only if we get the correct version number.

**Comment by barronh** [comment]
Great point. I realized that the version number was not correctly updated in the release. I'll add a __version__ import of version.version and release v3.2.1. Will that solve the problem?
