### ISSUE TITLE
problem with  pncboundaries.py

### ISSUE THREAD

**Issue by GolnooshB** [barronh/pseudonetcdf#14]
Hello Barronh,

I am trying to use the pbcboundaries.py command from this library, but I receive an error about mask files  

> pncboundaries.py ifile -v O3 -r TSTEP,mean outfile

AttributeError: 'PseudoNetCDFMaskedVariable' object has no attribute '_mask'

my domain is mostly over Canada, and I don't have any map or mask files for the domain.
Could you please help with this isuue?

Thanks,

**Comment by barronh** [comment]
Please add the platform, Python distribution, Python version, and numpy version. 

Barron Henderson
Asst. Professor, UF ESSIE EES
420 Black Hall; 352-846-2695

**Comment by barronh** [comment]
Never heard back.
