### ISSUE TITLE
IOError

### ISSUE THREAD

**Issue by yankodavila** [barronh/pseudonetcdf#15]
Hi Barron

I'm trying to convert a bpch file to netcdf and I'm getting this error:

[yanko@node29 RETRO]$ pncgen -f bpch 200001.2x25 200001.2x25.nc
Traceback (most recent call last):
  File "/cm/shared/apps/python/2.7.10/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/cm/shared/apps/python/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/cm/shared/apps/python/2.7.10/lib/python2.7/site-packages/PseudoNetCDF/pncgen.py", line 233, in <module>
    main()
  File "/cm/shared/apps/python/2.7.10/lib/python2.7/site-packages/PseudoNetCDF/pncgen.py", line 226, in main
    ifiles, options = pncparse(has_ofile = True, interactive = False)
  File "/cm/shared/apps/python/2.7.10/lib/python2.7/site-packages/PseudoNetCDF/pncparse.py", line 276, in pncparse
    ifiles.extend(pncprep(subarg)[0])
  File "/cm/shared/apps/python/2.7.10/lib/python2.7/site-packages/PseudoNetCDF/pncparse.py", line 322, in pncprep
    fs = getfiles(ipaths, args)
  File "/cm/shared/apps/python/2.7.10/lib/python2.7/site-packages/PseudoNetCDF/pncparse.py", line 365, in getfiles
    raise IOError('Unable to open path with %s(path, **%s)\n\tpath="%s"\n\terror="%s"' % (file_format, str(format_options), ipath, str(e)))
IOError: Unable to open path with bpch(path, **{})
	path="200001.2x25"
	error="invalid literal for int() with base 10: '1     710'"

It looks like it can't find the file which is funny because  the file is there.

[yanko@node29 RETRO]$ ls
200001.2x25  diaginfo.dat  tracerinfo.dat

[yanko@node29 RETRO]$ python
Python 2.7.10 (default, Dec  2 2015, 00:29:42)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2

[yanko@node29 RETRO]$ python -c "import numpy; print(numpy.version.version)"
1.11.2

**Comment by barronh** [comment]
It is definitely finding the path, but during the processing is getting a weird value. The errors from the command line are sometimes obscured. Try:

python -c "from PseudoNetCDF.geoschemfiles import bpch
f = bpch('200001.2x25 200001.2x25.nc')
"

That should provide a more clear error source. In this case, I doubt it will be super clear.

I'm guessing this is the RETRO inputs. You are facing a problem where the tracerinfo.dat file does not match the fixed width specification described in its header. Specifically, there is a misalignment of everything after the "FULL NAME" for O3df.

Look around line 1082 in the tracerinfo.dat. There is a less than sign in the middle of the word drydep (i.e., dr<ydep) in the "FULL NAME" of O3df. Remove the less than sign and it will probably work.

In order for it to work for me, I also had to remove some crazy characters from SAMODi, SAMODa, SAMODx lines. Run `file tracerinfo.dat` and you'll see that the file is ISO-8859 encoded... It should be an ASCII file. Select the special character in the FULL NAME after the word "min" in SAMODi and search for that character. You should find that it occurs on three of the SAMOD lines. Replace that character with a space.

That should solve the problem.

**Comment by barronh** [comment]
I am going to close assuming the problem has been found. If not, reopen.
