### ISSUE TITLE
Using PseudoNetCDF from local installation

### ISSUE THREAD

**Issue by arpitgit** [barronh/pseudonetcdf#17]
Hi,

I have locally installed PseudoNetCDF using pip and Anaconda3, like so:
**$ pip install --install-option="--prefix=$PREFIX_PATH" http://github.com/barronh/pseudonetcdf/archive/master.zip**

It creates a bin/ and a lib/ folder inside $PREFIX_PATH. However when I do:
**$ $PREFIX_PATH/bin/pncdump --help**

It gives me the following error:
_/home/arpitg/anaconda3/bin/python: Error while finding module specification for 'PseudoNetCDF.pncdump' (ModuleNotFoundError: No module named 'PseudoNetCDF')_

How do I correctly use my local installation of PseudoNetCDF package? Are there any environment variables which need to be set even after pip install?

Thanks,
Arpit

**Comment by barronh** [comment]
It looks like you have installed the module separate from your anaconda3.
It looks like anaconda3 is installed in your user directory, so you
shouldn't have had to use the --install-option at all. I recommend
uninstalling PseudoNetCDF from where ever it is and reinstalling without
that option.

**Comment by arpitgit** [comment]
Thanks for your prompt response. I removed the --install-option and installed PseudoNetCDF again, this time within anaconda3. However, now it gives me a ModuleNotFoundError for 'shapely'. Is this expected?

**[arpitg@nrlogin1 ~]$ pncdump --help**
_Traceback (most recent call last):
  File "/home/arpitg/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/arpitg/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/arpitg/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/__init__.py", line 38, in <module>
    from . import epafiles
  File "/home/arpitg/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/epafiles/__init__.py", line 3, in <module>
    from ._aqsraw import aqsraw
  File "/home/arpitg/anaconda3/lib/python3.6/site-packages/PseudoNetCDF/epafiles/_aqsraw.py", line 4, in <module>
    from shapely.wkt import loads
ModuleNotFoundError: No module named 'shapely'_


Regards,
Arpit

**Comment by barronh** [comment]
Try installing shapely, I'll fix this to be a option in the future.


Barron Henderson, Ph.D.
barronh.com; 352-682-3579

**Comment by arpitgit** [comment]
Thanks. Installation of shapely with geos did the trick.

Regards,
Arpit
