### ISSUE TITLE
TypeError: clean_showwarning() takes from 4 to 5 positional arguments but 6 were given

### ISSUE THREAD

**Issue by jimlawhk** [barronh/pseudonetcdf#19]
I installed Python-3.6.1 by using gcc (GCC) 5.1.0 on SLES 11 SP3. I can complete the installation and run the first test. i.e. 
     Dump an icartt file in CDL: pncdump -f ffi1001 HOX_DC8_20040626_R0.ict

However, I failed to run second test. i.e.
     Create a netcdf from an icartt file: pncgen -f ffi1001 HOX_DC8_20040626_R0.ict HOX_DC8_20040626_R0.nc

I get error as follows:

 pncgen -f ffi1001 HOX_DC8_20040626_R0.ict HOX_DC8_20040626_R0.nc
Traceback (most recent call last):
  File "/opt/share/Python-3.6.1.gcc/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/share/Python-3.6.1.gcc/lib/python3.6/runpy.py", line 125, in _get_module_details
    warn(RuntimeWarning(msg))
  File "/opt/share/Python-3.6.1.gcc/lib/python3.6/warnings.py", line 99, in _showwarnmsg
    msg.file, msg.line)
TypeError: clean_showwarning() takes from 4 to 5 positional arguments but 6 were given

Please advise what's wrong the my installation.

**Comment by barronh** [comment]
jimlawhk - This is an issue that was introduced with Python v3.6, but ultimately it is a problem with PseudoNetCDF's warning function. See #18 

The solution is actually quite simple and will be fixed in the live version.

In /opt/share/Python-3.6.1.gcc/lib/python3.6/site-packages/PseudoNetCDF/__init__.py

Change 
```
def clean_showwarning(message, category, filename, lineno, file=None):
```
to
```
def clean_showwarning(message, category, filename, lineno, file=None, line=None):
```

I will upload the fix ASAP.

**Comment by barronh** [comment]
Please reply to confirm that this fixes the problem.
