### ISSUE TITLE
Error when using pncgen

### ISSUE THREAD

**Issue by REpyprimer** [barronh/pseudonetcdf#21]

**Comment by barronh** [comment]
from PseudoNetCDF.pncgen import pncgen


Barron Henderson, Ph.D.
barronh.com; 352-682-3579

**Comment by REpyprimer** [comment]
Thanks, Baron!

If I want to drop one variable (FORM) from the gridded emissions file, I can do the following.

# -- Remove a species from a UAMIV Emissions File
from PseudoNetCDF import PNC
from PseudoNetCDF.pncgen import pncgen
pncargs = PNC('--format=uamiv', inpath)
infile = pncargs.ifiles[0]
del infile.variables['FORM']
vlist = getattr(infile, 'VAR-LIST')
setattr(infile, 'VAR-LIST', vlist.replace('FORM'.ljust(16), ''))
pncgen(infile, 'newpath.uamiv', format = 'uamiv')
# -- End

**Comment by REpyprimer** [comment]
Barron,

I try to remove 'I2' instead of 'FORM'. I still get a following error message,

pncgen(infile, outfile, format = 'uamiv')
  File "/disk41/jjung_linux/util/python/anaconda3/lib/python3.5/site-packages/PseudoNetCDF/pncgen.py", line 219, in pncgen
    return writer(ifile, outpath)
  File "/disk41/jjung_linux/util/python/anaconda3/lib/python3.5/site-packages/PseudoNetCDF/camxfiles/uamiv/Write.py", line 171, in ncf2uamiv
    spc_hdr[0]['DATA'][:, :, 0] = spc_names
ValueError: could not broadcast input array from shape (67,10) into shape (68,10)

When I do, 
infile.variables.keys()

I can still see 'I2' in the input file variable keys. I need to know how to update the keys.

Thanks - Jaegun

**Comment by barronh** [comment]
Does the code below work? Notice, I have to fix the "VAR-LIST" property. Last time, I deleted the key and then replaced "FORM".ljust(16) separately. This time, I use a variable so that I remove the same key from the dictionary that I remove from the VAR-LIST.

```
removekey = 'I2'
from PseudoNetCDF import PNC
from PseudoNetCDF.pncgen import pncgen
pncargs = PNC('--format=uamiv', inpath)
infile = pncargs.ifiles[0]
del infile.variables[removekey]
vlist = getattr(infile, 'VAR-LIST')
setattr(infile, 'VAR-LIST', vlist.replace(removekey.ljust(16), ''))
pncgen(infile, 'newpath.uamiv', format = 'uamiv')
```

**Comment by barronh** [comment]
If I want to remove both, then i could use a list of keys

```
removekeys = ['FORM', 'I2']
from PseudoNetCDF import PNC
from PseudoNetCDF.pncgen import pncgen
pncargs = PNC('--format=uamiv', inpath)
infile = pncargs.ifiles[0]
for removekey in removekeys:
    del infile.variables[removekey]
    vlist = getattr(infile, 'VAR-LIST')
    setattr(infile, 'VAR-LIST', vlist.replace(removekey.ljust(16), ''))

pncgen(infile, 'newpath.uamiv', format = 'uamiv')
```

**Comment by barronh** [comment]
Actually, its the "VAR" dimension!

```
removekeys = ['FORM']
inpath = '../TestData/CAMx/emiss/emiss.stl.12kmsmall.20020603.a1.bin'

from PseudoNetCDF import PNC
from PseudoNetCDF.pncgen import pncgen
pncargs = PNC('--format=uamiv', inpath)
infile = pncargs.ifiles[0]
for removekey in removekeys:
    del infile.variables[removekey]
    vlist = getattr(infile, 'VAR-LIST')
    setattr(infile, 'VAR-LIST', vlist.replace(removekey.ljust(16), ''))

infile.createDimension('VAR', len(infile.dimensions['VAR']) - len(removekeys))
pncgen(infile, 'newpath.uamiv', format = 'uamiv')
```

Tested and works.
