### ISSUE TITLE
using pseudonetcdf, netCDF4 error 

### ISSUE THREAD

**Issue by blroo** [barronh/pseudonetcdf#25]
Hi, I am trying to use the pseudonetcdf script pnclgobal2cmaq.py to prepare GEOS-Chem data as boundary conditions for a CMAQ simulation. When I try to run, I get the error below. Is the issue in locating a netCDF4 file, or is it something else? I am working on a linux cluster so it's possible certain paths aren't pointing in the right directions. I have pseudonetcdf installed in my user directory and I'm using a shared anaconda module. 

Thanks,
BR

Command Line:
`$ ./pncglobal2cmaq.py $M3DATA/geoschem/ts20150801.bpch --METBDY3D $M3DATA/mcip/4km/METBDY3D_India_Aug15 --METCRO3D $M3DATA/mcip/4km/METCRO3D_India_Aug15 --mapping=mappings.json  --outifolder=$M3DATA/geos2cmaq/ --outbfolder=$M3DATA/geos2cmaq/`

Error:
```
**PNC:/home/pseudonetcdf/PseudoNetCDF/conventions/ioapi/_ioapi.py:131:UserWarning:
  IOAPI_ISPH is assumed to be 6370000.; consistent with WRF
Traceback (most recent call last):
  File "./pncglobal2cmaq.py", line 1728, in <module>
    makeibcon(args)
  File "./pncglobal2cmaq.py", line 1327, in makeibcon
    newbcon = Dataset(args.NEWBCON, mode = 'ws', format = 'NETCDF3_CLASSIC')
  File "netCDF4/_netCDF4.pyx", line 1795, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:12271)
RuntimeError: No such file or directory
```

**Comment by barronh** [comment]
It looks like the outbcon folder does not exist. Make sure M3DATA is defined and that geos2cmaq is a folder within it.

**Comment by blroo** [comment]
Ah, that was it. Just had a typo in my path. Thank you.
