### ISSUE TITLE
PSURF and TMPU not defined

### ISSUE THREAD

**Issue by blroo** [barronh/pseudonetcdf#26]
Hi,

I am trying to use the pseudonetcdf script pnclgobal2cmaq.py to prepare GEOS-Chem data as boundary conditions for a CMAQ simulation. However, I believe PSURF and TMPU are not defined in my bpch files. I've tried using values from the standard atmosphere as specified in comment 5 of the pncglobal2cmaq.py script, however I get the error below.

Command:
`$ ./pncglobal2cmaq.py --expr="PSURF=np.ones_like(O3[:,0][:, None])*1013.25;TMPU=np.ones_like(O3[:])*np.array([287.7,286.9,286.0,285.2,284.3,283.4,282.6,281.7,280.7,279.8,278.9,277.9,276.8,275.3,273.6,271.8,270.0,268.2,265.8,262.8,259.7,256.4,252.9,249.2,245.2,241.0,236.4,230.5,223.6,216.8,216.6,216.6,216.6,216.6,216.6,216.6,216.6,217.5,219.8,222.0,225.3,233.6,250.5,269.2,260.0,237.7,214.3])[None,:47, None, None]" $M3DATA/geoschem/ts20150801.bpch --METBDY3D $M3DATA/mcip/4km/METBDY3D_India_Aug15 --METCRO3D $M3DATA/mcip/4km/METCRO3D_India_Aug15 --mapping=mappings.json  --outifolder=$M3DATA/geos2cmaq/ --outbfolder=$M3DATA/geos2cmaq/`

Error:
`Traceback (most recent call last):
  File "./pncglobal2cmaq.py", line 1718, in <module>
    ifiles, args = pncparse(has_ofile = False, parser = parser)
  File "/home/pseudonetcdf/PseudoNetCDF/pncparse.py", line 442, in pncparse
    out = pncprep(args)
  File "/home/pseudonetcdf/PseudoNetCDF/pncparse.py", line 611, in pncprep
    fs = [pncexpr(expr, f) for f in fs]
  File "/home/pseudonetcdf/PseudoNetCDF/pncparse.py", line 611, in <listcomp>
    fs = [pncexpr(expr, f) for f in fs]
  File "/home/pseudonetcdf/PseudoNetCDF/core/_functions.py", line 699, in pncexpr
    exec(comp, None, vardict)
  File "none", line 1, in <module>
ValueError: operands could not be broadcast together with shapes (24,40,25,21) (1,47,1,1)`

I am not clear on what this error means, or where to look for a solution. Am I using the expression correctly when executing the script?

Thanks,
BR

**Comment by barronh** [comment]
You TMPU is being entered as 47-layers, but your input data has only 40. Try replacing the `[None,:47,None,None]` with `[None,:40,None,None]`.

**Comment by blroo** [comment]
Hi Barron, that seemed to have resolved that issue, though I'm confused as to why. I see that 47 layers is specified, in `[None,:47,None,None]` however is the input data your referring to the `np.arry([287.7 .... 214.3])`? If so, that also has 47 values, so it would seem to me that it's okay.


Additionally, I now have a new error, copied below. Would you prefer I started a separate issue thread for this one?

New error:
`**PNC:/home/pseudonetcdf/PseudoNetCDF/conventions/ioapi/_ioapi.py:131:UserWarning:
  IOAPI_ISPH is assumed to be 6370000.; consistent with WRF
NO2, Traceback (most recent call last):
  File "./pncglobal2cmaq.py", line 1728, in <module>
    makeibcon(args)
  File "./pncglobal2cmaq.py", line 1527, in makeibcon
    outvals[:, pi] = np.interp(cp[::-1], rp[::-1], column[::-1])[::-1]
  File "/share/apps/software/rhel6/software/anaconda3/lib/python3.5/site-packages/numpy/lib/function_base.py", line 1271, in interp
    return compiled_interp(x, xp, fp, left, right)
ValueError: fp and xp are not of the same length.`

I'm not sure where xp and fp are defined or how to correct them. 

Thank you,
BR

**Comment by barronh** [comment]
Where did your GC inputs come from?

**Comment by blroo** [comment]
How do you mean?
My colleague ran the GEOS-Chem v10-01 and provided me with the .bpch, diaginfo.dat, smv2.log, and tracerinfo.dat files.

**Comment by barronh** [comment]
Are they ND49 files and what layers were output? It seems like you are trying to substitute approximate PSURF and std atmos TMPU. If ND49 files include these variables, then there is no need to supply them via expr. If you colleague did not include PSURF and TMPU and you don't want to rerun, then expr is supplying these variables. The expression must creat variables consistent with the layers in your output (e.g. 40)

**Comment by barronh** [comment]
Are they ND49 files and what layers were output? It seems like you are trying to substitute approximate PSURF and std atmos TMPU. If ND49 files include these variables, then there is no need to supply them via expr. If you colleague did not include PSURF and TMPU and you don't want to rerun, then expr is supplying these variables. The expression must creat variables consistent with the layers in your output (e.g. 40)

**Comment by blroo** [comment]
So the Geos-Chem outputs are ND49 files, in 60-min timesteps, including a whole bunch of tracers for levels 1-40. I've gotten updated files that do now include PSURF and TMPU. However, I still get the same error, even when excluding the PSURF and TMPU expressions since they are now in the files. 

Command:
`./pncglobal2cmaq.py $M3DATA/geoschem/ts20150726.bpch --METBDY3D $M3DATA/mcip/4km/METBDY3D_India_Aug15 --METCRO3D $M3DATA/mcip/4km/METCRO3D_India_Aug15 --mapping=mappings.json  --outifolder=$M3DATA/geos2cmaq/ --outbfolder=$M3DATA/geos2cmaq/`

Error:
'**PNC:/home//pseudonetcdf/PseudoNetCDF/conventions/ioapi/_ioapi.py:131:UserWarning:
  IOAPI_ISPH is assumed to be 6370000.; consistent with WRF
NO2, Traceback (most recent call last):
  File "./pncglobal2cmaq.py", line 1728, in <module>
    makeibcon(args)
  File "./pncglobal2cmaq.py", line 1527, in makeibcon
    outvals[:, pi] = np.interp(cp[::-1], rp[::-1], column[::-1])[::-1]
  File "/share/apps/software/rhel6/software/anaconda3/lib/python3.5/site-packages/numpy/lib/function_base.py", line 1271, in interp
    return compiled_interp(x, xp, fp, left, right)
ValueError: fp and xp are not of the same length.'

**Comment by barronh** [comment]
I suspect you need to update the mappings.json line

```
            "expression": "(hyam[:].reshape(1, -1).T + hybm[:].reshape(1, -1).T * PSURF[:][:, [0]].T).T * 100.",
```

to 

```
            "expression": "(hyam[:40].reshape(1, -1).T + hybm[:40].reshape(1, -1).T * PSURF[:][:, [0]].T).T * 100.",
```

If that doesn't work...

Re run it like this

```
python -i ./pncglobal2cmaq.py $M3DATA/geoschem/ts20150726.bpch --METBDY3D $M3DATA/mcip/4km/METBDY3D_India_Aug15 --METCRO3D $M3DATA/mcip/4km/METCRO3D_India_Aug15 --mapping=mappings.json --outifolder=$M3DATA/geos2cmaq/ --outbfolder=$M3DATA/geos2cmaq/
```

And when it crashes, type `import pdb; pdb.pm()` then type `u` and then type `rp.shape, column.shape` and post the results along with the first 22 lines of the mappings.json.  I can't be sure, but this suggests that the pressure output shape and the column shape are not the same.

**Comment by blroo** [comment]
I tried the first suggestion and got a bunch of messages similar to like these:

`**PNC:./pncglobal2cmaq.py:1434:UserWarning:
  Cannot evaluate any parts of 'TOL' = 'TOLU'; using default file
XYL, `
....
`**PNC:./pncglobal2cmaq.py:1593:UserWarning:
  Using old CON for:
OH, HO2, PAR, FACD, C2O3`


So then I tried your other suggestion, I get the same messages and then:
```
>>> import pdb
>>> pdb.pm()
> <stdin>(1)<module>()
(Pdb) u
*** Oldest frame
(Pdb) rp.shape
*** NameError: name 'rp' is not defined
(Pdb) column.shape
*** NameError: name 'column' is not defined
```

Though I'm not sure if I did this correctly.

The first 22 lines of the mappings.json file are:
```
{
    "comment1": "comments are added like this",
    "comment2": "Each line has the form \"Species\": {\"expression\": \"some expression\", \"unit\": \"some unit\"},",
    "comment3": "Variables with the output unit (micrograms/m**3) will be multiplied by air density (moles/m**3) and molar mass in the script. It should not be done in the expression.",
    "comment4": "Set \"manual_unit\": true to bypass script unit corrections",
    "comment5": "If you do not have PSURF and/or TMPU, you can use values from the standard atmosphere by adding --expr=\"PSURF=np.ones_like(O3[:,0][:, None])*1013.25;TMPU=np.ones_like(O3[:])*np.array([287.7,286.9,286.0,285.2,284.3,283.4,282.6,281.7,280.7,279.8,278.9,277.9,276.8,275.3,273.6,271.8,270.0,268.2,265.8,262.8,259.7,256.4,252.9,249.2,245.2,241.0,236.4,230.5,223.6,216.8,216.6,216.6,216.6,216.6,216.6,216.6,216.6,217.5,219.8,222.0,225.3,233.6,250.5,269.2,260.0,237.7,214.3])[None, :47, None, None]\"",
    "comment6": "more comments are added like this",
    "PRESS": {
            "expression": "(hyam[:40].reshape(1, -1).T + hybm[:40].reshape(1, -1).T * PSURF[:][:, [0]].T).T * 100.",
            "outunit": "Pa"
        },
    "AIRMOLDEN": {
            "expression": "(hyam[:40].reshape(1, -1).T + hybm[:40].reshape(1, -1).T * PSURF[:][:, [0]].T).T * 100. / 8.3144621 / TMPU[:]",
            "outunit": "moles/m**3",
            "for_stdatm_use": "((hyam[:, None] + hybm[:, None] * 1013.25) * 100 / 8.3144621 / np.maximum(216.6, 288.15 * ((hyam[:] + hybm[:] * 1013.25) / 1013.25)**C)[:NLAYS, None] * np.ones_like(O3).T).T"

        },
    "AIRMASSDEN": {
            "expression": "0.0289645 * (hyam[:40].reshape(1, -1).T + hybm[:40].reshape(1, -1).T * PSURF[:][:, [0]].T).T * 100 / 8.3144621 / TMPU[:]",
            "outunit": "kg/m**3",
            "for_stdatm_use_as_expr": "(0.0289645 * ((hyam[:, None] + hybm[:, None] * 1013.25) * 100 / 8.3144621 / np.array([287.7,286.9,286.0,285.2,284.3,283.4,282.6,281.7,280.7,279.8,278.9,277.9,276.8,275.3,273.6,271.8,270.0,268.2,265.8,262.8,259.7,256.4,252.9,249.2,245.2,241.0,236.4,230.5,223.6,216.8,216.6,216.6,216.6,216.6,216.6,216.6,216.6,217.5,219.8,222.0,225.3,233.6,250.5,269.2,260.0,237.7,214.3])[:NLAYS, None] * np.ones_like(O3).T).T"
        },
```

**Comment by barronh** [comment]
The messages you got were warnings, which means the first approach worked. 

In your case, TOLU is missing and the script is letting you know that it is relying on the default values that come from the BCONPROFILEPATH or the ICONPROFILEPATH. TOLU is not available in the standard oxidants run (use the SOA option if important). The other species (e.g., OH, HO2, etc) are not being mapped, so they are also defaulting to the standard CMAQ profile (hereafter PROFILE.). 

The PROFILE is supplied by the `--BCONPROFILEPATH` or the `--ICONPROFILEPATH` options. If you do not supply a "*CONPROFILEPATH", then one will be generated for you with minimum for all species. This is not terrible because GEOS-Chem provide the important species -- however, it is best practice to use a PROFILEPATH for both BCON and ICON. This is especially important when your inputs are missing some species.
