### ISSUE TITLE
UnboundLocalError: local variable 'dims' referenced before assignment

### ISSUE THREAD

**Issue by JiaoyanHuang** [barronh/pseudonetcdf#27]
Dr. Barron, 

I am using pncglobal2camq.py, I ran into this variable error.

My bpch file is in 3-hour interval for 2011 Jan from 20110101 0:00:00 (227904 hour since 9185-01-01 0:00:00) to 20110131 21:00

My MCIP file is in hourly interval fro 2011 Jan from 20110101 0:00:00 to 20110201 0:00:00

Here is message in log file 
**PNC:/nas/longleaf/home/jiaoyanh/.local/lib/python3.6/site-packages/PseudoNetCDF/conventions/ioapi/_ioapi.py:13:UserWarning:
  pyproj could not be found, so IO/API coordinates cannot be converted to lat/lon; to fix, install pyproj or basemap (e.g., `pip install pyproj)`
**PNC:/nas/longleaf/home/jiaoyanh/.local/lib/python3.6/site-packages/PseudoNetCDF/conventions/ioapi/_ioapi.py:131:UserWarning:
  IOAPI_ISPH is assumed to be 6370000.; consistent with WRF
Traceback (most recent call last):
  File "./pncglobal2cmaq.py", line 1487, in <module>
    makeibcon(args)
  File "./pncglobal2cmaq.py", line 1071, in makeibcon
    add_cf_from_ioapi(metbdy)
  File "/nas/longleaf/home/jiaoyanh/.local/lib/python3.6/site-packages/PseudoNetCDF/conventions/ioapi/_ioapi.py", line 311, in add_cf_from_ioapi
    add_lcc_coordinates(ifileo)
  File "/nas/longleaf/home/jiaoyanh/.local/lib/python3.6/site-packages/PseudoNetCDF/conventions/ioapi/_ioapi.py", line 270, in add_lcc_coordinates
    dims = [d for d in dims] # Why was I excluding time  if d != 'time'
UnboundLocalError: local variable 'dims' referenced before assignment

Is this error related to bpch and MICP file mismatching?

Thank you

Joey

**Comment by barronh** [comment]
In the error message, it tells you to install pyproj or basemap. Install either one and this problem will go away.
