### ISSUE TITLE
How to rename species name in CAMx emissions files

### ISSUE THREAD

**Issue by jaegunjung** [barronh/pseudonetcdf#28]
Hi Barron,

I would like to rename species variable names in CAMx gridded and point source emissions files. For example, PSO4 to PSO4_1. I can do this through xspcmap written in Fortran. But I am curious whether the Pseudonetcdf can do the same thing as it is more efficient to develop.

I have asked how to remove certain species, and you taught me to do following once I specified "spc" variable(s).

**del infile.variables[spc]
setattr(infile, 'VAR-LIST', vlist.replace(spc.ljust(16), ''))
infile.createDimension('VAR',len(infile.dimensions['VAR'])-nspc_to_remove)
pncgen(infile, outfile, format = 'uamiv')**

It must be very similar to above.

Thanks - Jaegun

**Comment by barronh** [comment]
Jaegun,

```
from PseudoNetCDF import PNC
from PseudoNetCDF.pncgen import pncgen

inpath = 'test.uamiv'
output = 'test.new'

pargs = PNC('-f=uamiv', '--rename=v,NO2,NOO', inpath)
infile = pargs.ifiles[0]
vlist=getattr(infile, 'VAR-LIST').replace('NO2'.ljust(16), 'NOO'.ljust(16))
setattr(infile, 'VAR-LIST', vlist)
pncgen(infile, outpath, format='uamiv')
```

-B

**Comment by jaegunjung** [comment]
Hi Barron,

Thank you for your guide. I successfully changed the variable names for the gridded CAMx emissions files. For the CAMx point source file, I simply replaced uamiv to point_source, but it does not work as follows.

**Traceback (most recent call last):
  File "/usr/people/jjung/util/python/my_tools/rename_CF2CMU/rename_CF2CMU_pt.py", line 26, in <module>
    pncgen(infile, outfile, format = 'point_source')
  File "/disk41/jjung_linux/util/python/anaconda3/lib/python3.5/site-packages/PseudoNetCDF/pncgen.py", line 219, in pncgen
    return writer(ifile, outpath)
  File "/disk41/jjung_linux/util/python/anaconda3/lib/python3.5/site-packages/PseudoNetCDF/camxfiles/point_source/Write.py", line 154, in ncf2point_source
    var = ncffile.variables[spc_key]
KeyError: 'PSO4'**

Is it possible to alter the CAMx point source file through Pseudonetcdf?

Thanks - Jaegun

**Comment by jaegunjung** [comment]
Hi Barron,

Can you also show me how to change two variable names?

Thanks - Jaegun

**Comment by barronh** [comment]
Re two variables: 
To change two names, add another ‘--rename=v,OLD,NEW’ option and a second correction (replace) to the vlist before assigning it to the file.

**Comment by jaegunjung** [comment]
Thanks, Barron. I got it.

Let me know if you have a chance to answer the previous question regards to CAMx point source files.

Jaegun

**Comment by barronh** [comment]
Jaegun,

In point_source files there are meta-data variables and true emission variables. The emission src are stored in SPC_NAMES. So for point_source files, replace "VAR-LIST" with "SPC_NAMES" in the code you used for area sources.

```
from PseudoNetCDF import PNC
from PseudoNetCDF.pncgen import pncgen

inpath = 'PseudoNetCDF/testcase/camxfiles/point_source/test.point_source'
outpath = 'test.newpoint'
pargs = PNC('-f=point_source', '--rename=v,NO2,NOO', inpath)
infile = pargs.ifiles[0]
vlist=getattr(infile, 'SPC_NAMES').replace('NO2'.ljust(16), 'NOO'.ljust(16))
setattr(infile, 'SPC_NAMES', vlist)
pncgen(infile, outpath, format='point_source')
```

In both these cases, the complexity arises from keeping the meta-data consistent. PseudoNetCDF isn't natively aware of many conventions.

**Comment by jaegunjung** [comment]
Thank you, Barron! It works.

Jaegun
