### ISSUE TITLE
CAMx UAM BC file header issue

### ISSUE THREAD

**Issue by jaegunjung** [barronh/pseudonetcdf#29]
Hi Barron,

Using Pseudonetcdf, I changed the variable names in a CAMx BC file. As Pseudonetcdf assigns a variable name for each edge, I renamed all four edges, and then saved it using,

pncgen(infile, outfile, format = 'lateral_boundary')

After that, I did "bin2asc" to make sure the BC file is correctly generated. In the CAMx BC file header, there is a loop for each boundary such as,

**Loop from 1 to 4 boundaries:
    ione, iedge, ncell, (icell(n),idum,idum,idum,n=1,ncell)

iedge - Integer boundary edge number (1=west, 2=east, 3=south, 4=north)
icell    - Integer index of first cell modeled (edges 1,3), or last cell modeled (edges 2,4): if "0", this row/column is omitted from simulation**

For edges 2,4, the file generated by Pseudonetcdf shows the first cell modeled instead of the last cell. I don't know whether it will make CAMx crash or not. But, it is better to be fixed.

Also, it took 16 minutes to process a 200 MB BC file. As Pseudonetcdf flags each edge as one variable and syncing four variables to one, it is not a big surprise. But, it takes considerably much larger than point source or gridded emissions files with similar file size.

Thanks - Jaegun

**Comment by barronh** [comment]
Jaegun,

Thanks for the heads up. Although the CAMx BC writer is mostly functional, it is not as mature as the uamiv reader/writer combo. I've fixed the problem you highlighted and verified that the variables are identical when read from the test case and written. A binary diff still shows changes, which appear to be related to the ione,ione,nx,ny line. In the test case, ione is set to 0. The writer, however, writes this as a one (1), which is consistent with the user guide.

I also enhanced the speed.

You can copy the Write.py[1] file over your existing one and it should be faster and have this issue resolved. Please confirm.

While I was at it, I fixed a couple Python3 compatibility issues with the older met input readers.

[1] https://raw.githubusercontent.com/barronh/pseudonetcdf/master/src/PseudoNetCDF/camxfiles/lateral_boundary/Write.py


Barron

**Comment by jaegunjung** [comment]
Hi Barron,

Thanks for the fast response. It now takes only one minute. For the header of BC files, the CAMx user guide is not very detailed. When you prepare the header for EAST, you actually print NCOLS - 1 instead of NROWS - 1. Same goes for NORTH. Here are changes that I made on top of the Write.py that you provided.

**#>diff Write_new.py Write_new_a0.py
103c103,104
<                 icell = nbcell - 1
---
>                 if ename == 'EAST' : icell = NCOLS - 1
>                 if ename == 'NORTH': icell = NROWS - 1**

I am not sure what you meant by,

**While I was at it, I fixed a couple Python3 compatibility issues with the older met input readers.**

This statement is not related to this topic. In other words, Write.py is not related to the older met input readers. It is just FYI of updates made in Pseudonetcdf in Python3, right?

Thanks - Jaegun

**Comment by barronh** [comment]
I have applied your correction. Thank you!

Yes, the compatibility thing was unrelated, but I didn't want you to be surprised that other files changed.

**Comment by jaegunjung** [comment]
Hi Barron,

I applied my job script that changes 10 variable names from 1.5G point source file and it worked within five minutes or so. But when I try 4.1G point source file, it just hangs.

Is it possible to solve this issue like one you did for BC?

Thanks - Jaegun

**Comment by barronh** [comment]
I've updated the PseudoNetCDF/camxfiles/point_source/Write.py. See if that helps. 

The write function being used automatically defaults file buffering to your machines default (probably 8192).

```
import io
print(io.DEFAULT_BUFFER_SIZE)
```

Right now, I am using a time-chunk approach to increase the speed by bypassing the default buffer. I may retool these updates in the future to use the open "buffering" option and set it to an arbitrarily high value (e.g., 100MB).

**Comment by barronh** [comment]
In the future, please start a new issue and reference the old issue.
