### ISSUE TITLE
Append a new variable 

### ISSUE THREAD

**Issue by rsurya1979** [barronh/pseudonetcdf#30]
Hi Barron - Hope you can help me. I'm trying to append a variable to the CAMx restart file. I can even copy the original variable into a new one with a different variable name if there is an option for it. 

So in order to append a new variable I started a script as follow:
###########################################################################
import os
src = 'newpath.uamiv'
dst = 'outpath.uamiv'

from PseudoNetCDF import PNC
from PseudoNetCDF import PseudoNetCDFFile
from PseudoNetCDF.pncgen import pncgen
pncargs = PNC('--format=uamiv', src)
infile = pncargs.ifiles[0]
tsp_nc = infile.dimensions['TSTEP']
lay_nc = infile.dimensions['LAY']
row_nc = infile.dimensions['ROW']
col_nc = infile.dimensions['COL']
#dim_nc = infile.dimensions
#print (dim_nc)
newvar = infile.createVariable('O3N001008','f4',('TSTEP','LAY','ROW','COL'))
#print (infile.variables)
#print (dim_nc)
newvar.units ='ppm'
newvar.long_name = 'O3N001008'
infile.createDimension('VAR', len(infile.dimensions['VAR']) + len(newvar))
pncgen(infile, dst, format = 'uamiv')
############################################################################

**PNC:/home/mark/Downloads/anaconda3/lib/python3.5/site-packages/PseudoNetCDF/conventions/ioapi/_ioapi.py:134:UserWarning:
  IOAPI_ISPH is assumed to be 6370000.; consistent with WRF
Traceback (most recent call last):
  File "append_var.py", line 22, in <module>
    pncgen(infile, dst, format = 'uamiv')
  File "/home/mark/Downloads/anaconda3/lib/python3.5/site-packages/PseudoNetCDF/pncgen.py", line 219, in pncgen
    return writer(ifile, outpath)
  File "/home/mark/Downloads/anaconda3/lib/python3.5/site-packages/PseudoNetCDF/camxfiles/uamiv/Write.py", line 182, in ncf2uamiv
    spc_hdr[0]['DATA'][:, :, 0] = spc_names
ValueError: could not broadcast input array from shape (59,10) into shape (60,10)

############################################################################

Any help or advice you can provide would be appreciated. Thanks

Surya

**Comment by barronh** [comment]
Try adding the new species name to VAR-LIST. Add the code below before calling pncgen. 

'''
vlist = getattr(infile, 'VAR-LIST')
vlist += newvar.long_name.ljust(16)
setattr(infile, 'VAR-LIST', vlist)
'''

**Comment by rsurya1979** [comment]
Thanks Barron. It worked.
