### ISSUE TITLE
pncmap.py - Can I take more than one input file and combine?

### ISSUE THREAD

**Issue by jaegunjung** [barronh/pseudonetcdf#33]
Hi Barron,

I am also interested in comparing two different files for the same species. Is it possible to do this through pncmap.py? If so, can you present an example for me?

Thanks - Jaegun

**Comment by barronh** [comment]
Look at the ‘—op-typ’ option. 

‘’’
pncmap.py -v O3 —op-typ=“-“ inpath1 inpath2 outpath 
‘’’

**Comment by barronh** [comment]
p.s., `pncmap.py -h` Will show lots of options and instructions.
