### ISSUE TITLE
pncmap.py - Can I combine two different variables from multiple input files?

### ISSUE THREAD

**Issue by jaegunjung** [barronh/pseudonetcdf#34]
Hi Barron,

Thanks for replying my previous question. In my case, I need to combine two different variables from multiple input files. For example,

"PNO3 from infile1" - "PNO3_1 from infile2"

P.S. I did pncmap.py -h, and it shows all the options but ends with some error messages such as,

*ifile or pnc are required
Traceback (most recent call last):
  File "/usr/people/jjung/util/python/anaconda3/bin/pncmap.py", line 11, in <module>
    main()
  File "/usr/people/jjung/util/python/anaconda3/bin/pncmap.py", line 8, in main
    makemaps(args)
  File "/disk41/jjung_linux/util/python/anaconda3/lib/python3.5/site-packages/PseudoNetCDF/plotutil/pncmap.py", line 18, in makemaps
    ifile = ifiles[0]
IndexError: list index out of range

Am I only one who see this? If so, I may have some problem when I install pseudonetcdf.

Thanks - Jaegun

**Comment by barronh** [comment]
Re -h: Give pncmap.py -h an argument and the error goes away. As you say, the options are shown any way. 

Re differences of different variables from different files:

Combine --merge and --expr 

Or

Combine --rename and --op-typ with -- and --sep to force order of operation.

**Comment by jaegunjung** [comment]
I did "pncmap.py -h", but I still got the error messages at the end.

Is "Combine" a program belong to the pseudonetcdf pacakge? I cannot find it.

Thanks - Jaegun

**Comment by barronh** [comment]
@jaegunjung - don't worry about the error message after the `-h`. Read the help above the error.

"Combine" was being used as a verb ;). The command below uses `--merge` to merge two files' variables and then applies the `--expr`. In the case below, I am looking at an ratio and the denominator is sometimes zero, so I add the masking functionality and the normalizer. Obviously the units on what I am doing need to be thought about. I'm using it as an arbitrary expression using two variables from different files.

```
pncmap.py -s LAY,0 -r TSTEP,mean -f uamiv -v HNO3CoverDD --norm="LogNorm(vmax=10)" --mask=invalid -- --expr="HNO3CoverDD=HNO3/HNO3_DD" --merge CAMx.v6.40.midwest.36.12.noMPI.20020603.depn.grd01 CAMx.v6.40.midwest.36.12.noMPI.20020603.avrg.grd01 test
```

**Comment by jaegunjung** [comment]
I got it. Thank you!
