### ISSUE TITLE
How to append one time record into "TFLAG" array for the TSTEP column of "UNLIMITED"?

### ISSUE THREAD

**Issue by jaegunjung** [barronh/pseudonetcdf#36]
Hi Barron,

I want to append one hour record into an existing one day CAMx (gridded) output file which has 24 hourly data in it. The output file will have 25 hourly data. For handling IOAPI file, I can do this once I open the file with the command below,

```
fout_path = /path/.../file.ncf
fout = ncdf4.Dataset(fout_path,'a',format="NETCDF3_CLASSIC")
fout.variables['TFLAG'][24,:,0] = np.array([0]) #The 24 refers to the 25th data record
```

The fout.variables['TFLAG'] has (u'TSTEP', u'VAR', u'DATE-TIME') dimension. When I first opened the file, The 'TSTEP' dimension is,

`TSTEP = UNLIMITED ; // (24 currently)`

After I add one record, this dimension becomes,

`TSTEP = UNLIMITED ; // (25 currently)`

I think it is possible as TSTEP is UNLIMITED.

But for CAMx file, it is not possible. I did following commands,

```
from PseudoNetCDF import PNC
pncargs = '--format=uamiv,mode="r+"'
newf = PNC(pncargs, fout_path)
fout = newf.ifiles[0]
```
This has TSTEP dimension as follows,
`TSTEP = UNLIMITED // (24 currently)`

After that, I did,

`fout.variables['TFLAG'][24,:,0] = np.array([0]) #The 24 refers to the 25th data record`

It gives me the following error messages,

`IndexError: index 24 is out of bounds for axis 0 with size 24
`

I cannot understand this as TSTEP is UNLIMITED as the IOAPI file. I tried to change mode from "r+" to "a" as I opened the IOAPI file, but "a" option is not available.

Can I concatenate the CAMx files through PseudoNetcdf like the netCDF4 module?

Thanks - Jaegun

**Comment by barronh** [comment]
The uamiv file structure is based on memmap, which is not compatible with unlimited. You can create a file with an extra time by “stacking” files on the TSTEP dimension. The version below appends the last time as a duplicate. 

```
from PseudoNerCDF import PNC
from PseudoNerCDF.pncgen import pncgen
from PseudoNerCDF.sci_var import stack_files
outpath = ‘out.uamiv’
inpath =‘/path/test.uamiv’
infile1 = PNC(‘--format=uamiv’, inpath).ifiles[0]
infile2 = PNC(‘--format=uamiv’, ‘--slice=TSTEP,-1’, inpath).ifiles[0]
infile.variables[‘TFLAG’][-1,:,0] += 1
infile.variables[‘TFLAG’][-1,:,1] = 0
newfile = stack_files([infile1, infile2], ‘TSTEP’)
pncgen(newfile, outpath, format = ‘uamiv’)
```

Typed on iPhone without testing. Please post any corrections

**Comment by jaegunjung** [comment]
Barron,

Thanks for the quick answer. For the following command line, it gives 0 instead of 1 for TSTEP dimension,

infile2 = PNC(‘--format=uamiv’, ‘--slice=TSTEP,-1’, inpath).ifiles[0]

I tested with,

infile2 = PNC(‘--format=uamiv’, ‘--slice=TSTEP,1’, inpath).ifiles[0]

It creates TSTEP = 1, and the rest of commands work fine.

I don't need to know append the last time record so I am fine with this.

Thank you.
Jaegun
