### ISSUE TITLE
How to convert CMAQ output from IOAPI to classic NC file like WRF output 

### ISSUE THREAD

**Issue by LeonTHLin** [barronh/pseudonetcdf#46]
Hello @barronh

I operate CMAQ model and want to visualize the result. But I meet some problem with IOAPI. 
So I need to add CF metadate into original CMAQ output like WRF output no matter NC3 or NC4. I notice your website showed it's possible to add metadate with pseudonetcdf simply (http://www.barronh.com/software/tutorials/making-cf-compliant). But I spent long time but it's still not work.
May I ask to tell me more in detail?

So appreciate.

Regards,
Leon

**Comment by LeonTHLin** [comment]
Thanks.
But I got a error message after process like below:

Populating longitude_bounds
AttributeError: __getattribute__
Exception ignored in: 'netCDF4._netCDF4.Dataset.__dealloc__'
AttributeError: __getattribute__

The output file was still created and allow ncdump to grab a head message. Does it mean I just ignore this Error?

**Comment by barronh** [comment]
Yes, ignore the warning. This is a python 2 vs 3 object issue that I have not been able to fix.

**Comment by LeonTHLin** [comment]
It did work.
Then I want change some parameter from TSTEP, LAY, ROW and COL to Time,  level. latitude and longitude by ncrename in file created by pncopen.save process.
But after ncrename the error message show like below while I used ncdump:

NetCDF: HDF error

Is it could be fix or is it better to output NETCDF3?

**Comment by LeonTHLin** [comment]
Thanks,

It worked for me but the Projection of output showed Error as below:

Projection:    Error: Unsupported projection

after dealing with tdcfdump

Is it could be fix?

**Comment by barronh** [comment]
You’ll have to be more clear. What gave you that error?

You might need to add properties that are expected by your software. Or rename coordinate variables. 

Panoply can visualize both wrf and IOAPI. No sure what you are using.

**Comment by LeonTHLin** [comment]
Seems CCTM output lossed some coordinate information resulted in this Error but this information existed in METCRO3D output. 
I tried to combine two file into a larger one and fixed the problem. 
Is it possible to combine two files by PseudoNetCDF and cut each forecast time to independent file?

Thank you some much

**Comment by barronh** [comment]
The CCTM files did not loose coordinate information. They have meta-data that can be interpreted by Panoply or PseudoNetCDF.  Panoply reads IOAPI files by heuristically determining the way to infer coordinates. 

When you renamed the dimensions, which you asked to do, the netcdf-java library would no longer heuristically infer IOAPI conventions. That would make it appear to have "lost" coordinate information. 

I understand that you are trying to use a software to visualize results, but I still don't know what software cannot read the projection. What software are you using that gives you the error?

What are you trying to accomplish? If it is just visualizing the files, don't modify them and use Panoply.

So the questions that you must answer are:
1) What software are you using that gives you the error?
2) What exactly are you trying to do? Be detailed and include detailed substeps.

**Comment by LeonTHLin** [comment]
Sorry let you confuse.

I want to visualize data with commercial software Visual Weather by IBL company.
Unfortunately, IOAPI isn't available for this software so I need to add CF information into raw data.
METCRO3D worked fine but CCTM had showed some error if deal with tdcfdump after process of  PseudoNetCDF:

Name:           longitude
Standard name:  longitude
Units:          degrees_east
Time reference: MISSING
Projection: Error: Unsupported projection

I combined METCRO3D and CCTM output first before process with PseudoNetCDF and then it worked.
So I want to know how to combine two files and separate each forecast time into individual file, all by  PseudoNetCDF.

Thanks so much.

**Comment by barronh** [comment]
What is tdcfdump? What data did you have to combine?

**Comment by LeonTHLin** [comment]
Seems tdcfdump is a widget from Visual Weather. Please forget it.

I want to merge METCRO3D and CCTM model output produced by CMAQ and separate each forecast time into individual new file.
I wonder all process could be done by PseudoNetCDF at one time, doesn't it?

Thanks for your help.

**Comment by barronh** [comment]
It is easy to merge processes and separate into times.

```
# Import Library
import PseudoNetCDF as pnc

# Make a path pattern for outputs
outpathtmp = 'output%02d.nc'

# Open input files with same dimensions
conc1 = pnc.pncopen('/path/to/CCTM_CONC.nc', format='ioapi')
met1 = pnc.pncopen('/path/to/METCRO3D.nc', format='ioapi')

# If using met and average conc (ACONC), average met or take time step 1
# similar accommodations can be made for layer 1 only (e.g., LAY=0)
# metstart = met1.sliceDimensions(TSTEP=slice(0, 24))
# metend = met1.sliceDimensions(TSTEP=slice(1, None))
# met1 = metstart + metend

# Copy file 1 to memory, not totally necessary, but easiest
outf = conc1.copy()

# Which keys from met file will be copied
keys2copy = ['PRES']

for k in keys2copy:
    outf.copyVariable(met1.variables[k], key=k)

for hi in range(25):
    outf.sliceDimensions(TSTEP=hi).save(outpathtmp % hi, format='NETCDF3_CLASSIC')

```

**Comment by fard792** [comment]
hi all
i want to change center of domain in emission inventory of CMAQ  .ncf  file format , my center of domain have to shift to other lat and lon place
by which command or sofware i can change metadata or variable into ncf files ?
thank you very much
fard792@gmail.com

**Comment by barronh** [comment]
It is hard for me to tell exactly what you want to do. Reassigning the meta-data to shift is definitely possible, but it may mean that the data is no longer consistent with the metadata. Shifting the center could mean several things: creating a windowed subset that is symmetric around another point (XCENT/YCENT unchanged, XORIG/YORIG/NCOLS,NROWS change), or reassigning the XCENT/YCENT/P_GAM without modifying the underlying data structure -- even though the data may not be spatially consistent. In some cases, the projection may no longer be reasonable.

A quick answer is that it is easy to change metadata on IOAPI files.

If you want tools that help you do predefined tasks, look at the IOAPI manual  https://www.cmascenter.org/ioapi/documentation/all_versions/html/AA.html#coordstuff

If you want to modify the metadata more flexibly, you can use nco (via ncatted), PseudoNetCDF (via pncload or pncgen).

```
python -ic "import PseudoNetCDF as pnc
# warning the plan is to edit this file
infile = pnc.pncopen('emis_ioapi.nc', format='netcdf', mode='r+')
# this is the old value, so no real change is made
infile.XCENT = -97.
# this is the old value, so no real change is made
infile.YCENT = 40.
infile.close()
"
```

With more detail, this might be a better question of the CMAQ list serve. See the cmascenter.org.

**Comment by ChrisTang19** [comment]
hi all
i want to convert CMAQ output from IOAPI to  WRF output NC file, 
by which command or sofware i can change it?
thank you very much

**Comment by barronh** [comment]
@ChrisTang19 - please start a new issue. I will respond there.

**Comment by ChrisTang19** [comment]
@barronh  
Thanks,
I started a new issue about this question, 
https://github.com/barronh/pseudonetcdf/issues/110
