### ISSUE TITLE
Got error message: NetCDF: HDF error after pncopen and ncrename 

### ISSUE THREAD

**Issue by LeonTHLin** [barronh/pseudonetcdf#47]
Hello:

It did work that adding CF metadata to CMAQ output.
Then I want change some parameter from TSTEP, LAY, ROW and COL to Time, level. latitude and longitude by ncrename in file created by pncopen.save process.
But after ncrename the error message show like below while I used ncdump:

NetCDF: HDF error

Is it could be fix or is it better to output NETCDF3 by pncopen.save?

**Comment by barronh** [comment]
No need for a separate issue, see #46
