### ISSUE TITLE
pncglobal2cmaq: ValueError: two fields with the same name

### ISSUE THREAD

**Issue by blroo** [barronh/pseudonetcdf#48]
Hi, I am trying to use pncglobal2cmaq. 

I have successfully executed pncglobal2cmaq before with a different input data set. I am trying with new input data, and now it returns the error below. It seems likely that the issue is with the input data, since nothing else was changed, however I'm not sure how to interpret the response below in order to locate the issue.

Any recommendations?

```
[brooney@fram-login-5-2 scripts]$ ./pncglobal2cmaq.py /home/brooney/CMAQ_IndiaAug15/data/geoschemfiles/ts20150716.bpch --METBDY3D /home/brooney/CMAQ_IndiaAug15/data/mcip/bare_v5.1/4km/METBDY3D_India_Aug15 --METCRO3D /home/brooney/CMAQ_IndiaAug15/data/mcip/bare_v5.1/4km/METCRO3D_India_Aug15 --mapping=mappings.json --outifolder=/home/brooney/CMAQ_IndiaAug15/data/geos2cmaq/ --outbfolder=/home/brooney/CMAQ_IndiaAug15/data/geos2cmaq/
Traceback (most recent call last):
  File "/home/brooney/pseudonetcdf/PseudoNetCDF/pncparse.py", line 661, in getfiles
    f = allreaders[file_format](ipath, **format_options)
  File "/home/brooney/pseudonetcdf/PseudoNetCDF/geoschemfiles/_bpch.py", line 780, in __init__
    time_type = dtype([(k, dtype([(str('header'), _datablock_header_type), (str('data'), d)])) for k, d in zip(keys, data_types)])
ValueError: two fields with the same name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./pncglobal2cmaq.py", line 1718, in <module>
    ifiles, args = pncparse(has_ofile = False, parser = parser)
  File "/home/brooney/pseudonetcdf/PseudoNetCDF/pncparse.py", line 419, in pncparse
    ifiles.extend(pncprep(subarg)[0])
  File "/home/brooney/pseudonetcdf/PseudoNetCDF/pncparse.py", line 607, in pncprep
    fs = getfiles(ipaths, args)
  File "/home/brooney/pseudonetcdf/PseudoNetCDF/pncparse.py", line 666, in getfiles
    raise oute from e
OSError: Unable to open path with bpch(path, **{'nogroup': True})
        path="/home/brooney/CMAQ_IndiaAug15/data/geoschemfiles/ts20150716.bpch"
```

Thanks,
B

**Comment by barronh** [comment]
My guess is that either you have the wrong tracerinfo.dat file or the file has multiple tracer keys and is being read with nogroup=True. Try changing the reader with the 

‘’’
-f “bpch,nogroup=(‘IJ-AVG-$’,’DAO-3D-$’,’PEDGE-$’)”
‘’’

**Comment by barronh** [comment]
Run `pncglobal2cmaq.py with -h` to view the options. One option is the `-f` format option. By default, it is set to `bpch,nogroup=True`. That means that it is expecting to read a bpch file where all the species in the file are unique (i.e., NO2 is only available from 'IJ-AVG-$'). Sometimes, extra options have been used and the output file has NO2 as an emission and as a 'IJ-AVG-$'. This is certainly true if you are using the standard time average outputs. When an output does not meet this criteria, another format specification must be used. 

For the standard outputs, I recommend using `-f benchmark` in #7.  You can try that. If it doesn't work, you can use a more custom approach like the one I specified above. It would look like:

```
pncglobal2cmaq.py -f benchmark ...
```

or

```
pncglobal2cmaq.py -f "bpch,nogroup=('IJ-AVG-$','DAO-3D-$','PEDGE-$')" ...
```

where the `...` is replaced by all your normal options. The `-f` option also allows you to use netcdf files or CAMx files or anything that is supported by pseudonetcdf. The hardest part can be knowing what you have and what you need.  If you're not sure what is in your file, try the command below.

```
pncdump --header -f bpch example.bpch
```

Note any duplicate species (e.g., IJ-AVG-$_NO and NO-AN-$_NO). Decide which one you want evaluated as NO in boundary conditions (here IJ-AVG-$) and then ensure that it is in the nogroup list (see above).

**Comment by blroo** [comment]
Thank you! pncglobal2cmaq now runs successfully.
