### ISSUE TITLE
cb6 cmaq chemistry 

### ISSUE THREAD

**Issue by ZaraHssn** [barronh/pseudonetcdf#64]
Hi, I am trying to get CMAQ BC/IC from GEOS-Chem outputs and planning to use pncglobal2cmaq.py, does the package support cb6 chemistry scheme and how do I download mappings.json?

**Comment by barronh** [comment]
I do have cb6 mapping files that are compatible with CMAQ and v11 GEOS-Chem. One reason that I am moving away from the pncglobal2cmaq.py script is that it was hard to package up the mapping files in this more general library. See http://github.com/barronh/aqmbc.
