### ISSUE TITLE
GEOS-Chem Benchmarks How To

### ISSUE THREAD

**Issue by gc13141112** [barronh/pseudonetcdf#66]
pncglobal2cmaq.py use which file from http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/ obtain data to process ic and bc file

**Comment by barronh** [comment]
First, I am assuming your are following an approach like that described in https://github.com/barronh/pseudonetcdf/issues/7#issuecomment-161059006. That code is expecting bpch files, not the new netcdf files (GC version > 10). So, you'll need a the *.bpch files. Depending on the version of GEOS-Chem benchmark, they are sometimes available in a bpch.tar.gz.

When you use pncglobal2cmaq.py you need a mappings.json file. That has all the translations between GEOS-Chem and CMAQ. The contents of the mappings.json file needs to be specific to both the CMAQ and GEOS-Chem versions/mechanisms. The versions/mechanisms of those models that you want will depend on the science/application goals.


Most of the mappings are described in Henderson et al., 2014 (https://doi.org/10.5194/gmd-7-339-2014). That was specific to GEOS-Chem v8/v9 with SOA chemistry and CMAQ v5.0.2 w/ CB05 or SAPRC07 and AE6. Using newer mechanisms and/or versions requires updates to the mappings.  The inorganic gas- and aerosol- phases has been relatively stable, and has changed a lot -- so it doesn't need typically need updating. The biogenic gases and aerosols are more likely to have been updated between versions.

I am working on providing a thorough description of the options, but for now you can request a specific pairing request and I can help. You need to answer the following questions:

- GEOS-Chem version?
- GEOS-Chem mechanism option (standard, tropchem, SOA, etc)?
- CMAQ version (v4.7, v5.0.2, v5.2.1, v5.3)?
- CMAQ gas mechanism (CB05, CB6r3, SAPRC99, SAPRC07)?
- CMAQ aerosol mechanism (AE5, AE6 and for v5.2 and beyond AE6 nvPOA or AE6 pcSOA or AE7)?


p.s., In general, please provide more of a description. I am guessing at an answer here.

**Comment by gc13141112** [comment]
Thank you for your reply! I want use this script to obtain CMAQ v5.2 (CB05AE6 or CB6r3AE6 ) IC and BC file by the MOZART-4 data or WACCM data (https://www.acom.ucar.edu/wrf-chem/mozart.shtml). Please advice!

**Comment by barronh** [comment]
The majority of the effort would be in developing the appropriate mappings.json for MOZART-4 and WACCM. You could take guidance from mappings provided in camx's IC/BC software.

I have been migrating this functionality into a separate project to help manage these mappings and modularize the steps.

https://github.com/barronh/aqmbc

**Comment by gc13141112** [comment]
Thank you again!
