### ISSUE TITLE
pncglobal2cmaq.py - encoding error

### ISSUE THREAD

**Issue by blroo** [barronh/pseudonetcdf#67]
Hi,

In trying to run pncglobal2cmaq, I get the following error:

```
/home/brooney/anaconda3/lib/python3.7/site-packages/numpy/lib/npyio.py:2242: VisibleDeprecationWarning: 
        Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default. 
Traceback (most recent call last): 
  File "./pncglobal2cmaq.py_test", line 1731, in <module> 
    makeibcon(args) 
  File "./pncglobal2cmaq.py_test", line 1291, in makeibcon 
    mappings_file = json.load(open(args.mapping, mode = 'r')) 
  File "/home/brooney/anaconda3/lib/python3.7/json/__init__.py", line 296, in load 
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw) 
  File "/home/brooney/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads 
    return _default_decoder.decode(s) 
  File "/home/brooney/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode 
    obj, end = self.raw_decode(s, idx=_w(s, 0).end()) 
  File "/home/brooney/anaconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode 
    raise JSONDecodeError("Expecting value", s, err.value) from None 
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
````

Is this an issue with the numpy i've installed with python3.7?  Or an issue with the json.decoder?

Thanks,
Brigitte

**Comment by barronh** [comment]
@blroo - I updated your comment to treat the output as a block. This helps to highlight two things. First, the encoding is part of a warning. That helps us to know that it is not the root of the problem.  The script, which it appears you've copied and renamed, is trying to read the mapping input (usually `mappings.json`; path is specified by the `--mapping` option). 

The error says there is a problem on line 1, column 1. An error on line 1 column 1 makes me think the file is not right at all. Take a look at https://github.com/barronh/pseudonetcdf/wiki/BCON-Mappings-File

**Comment by blroo** [comment]
Thanks Barron, turns out I just had accidentally edited the mappings.json file incorrectly. pncglobal2cmaq seems to be working now.
