### ISSUE TITLE
BCON with 1 TSTEP

### ISSUE THREAD

**Issue by JiaoyanHuang** [barronh/pseudonetcdf#8]
Hey Dr. Henderson, 

 I used the python codes to generate CMAQ icon and bcon from GEOSChem output, it only have 1 TSTEP for BCON, they are daily data, so I expect they should have 25 TSTEP

netcdf full_bcon_20130114 {
dimensions:
        TSTEP = UNLIMITED ; // (1 currently)

everything else looks fine, 

netcdf METCRO3D_CONUS_36_20130114 {
dimensions:
        TSTEP = UNLIMITED ; // (25 currently)

do you have any suggestion or thoughts?

Thank you

**Comment by barronh** [comment]
It will depend on the GEOS-Chem data that you used as input.


Barron Henderson, Ph.D.
Asst. Professor, University of Florida
Dept. of Environmental Engineering Sciences
420 Black Hall; 352-846-2695

**Comment by JiaoyanHuang** [comment]
Dr. Barron, 

I wrote this code to do this for me 

_#!/bin/bash

STDATE="20130101"
ENDATE="20130101"
#echo $STDATE
#echo $ENDATE

while [ $STDATE -le $ENDATE ]; do
cp -p /home/jiaoyanh/work/MCIP_data/36CONUS_12WUS_2013/mcip_d01/METBDY3D_CONUS_36_$STDATE.gz /home/jiaoyanh/pseudonetcdf/Full_chemistry/201301/inputs
cp -p /home/jiaoyanh/work/MCIP_data/36CONUS_12WUS_2013/mcip_d01/METCRO2D_CONUS_36_$STDATE.gz /home/jiaoyanh/pseudonetcdf/Full_chemistry/201301/inputs
cp -p /home/jiaoyanh/work/MCIP_data/36CONUS_12WUS_2013/mcip_d01/METCRO3D_CONUS_36_$STDATE.gz /home/jiaoyanh/pseudonetcdf/Full_chemistry/201301/inputs
cp -p /home/jiaoyanh/work/MCIP_data/36CONUS_12WUS_2013/mcip_d01/METDOT3D_CONUS_36_$STDATE.gz /home/jiaoyanh/pseudonetcdf/Full_chemistry/201301/inputs


cd /home/jiaoyanh/pseudonetcdf/Full_chemistry/201301/inputs
gunzip METBDY3D_CONUS_36_$STDATE.gz
gunzip METCRO2D_CONUS_36_$STDATE.gz
gunzip METCRO3D_CONUS_36_$STDATE.gz
gunzip METDOT3D_CONUS_36_$STDATE.gz

cd ../

inputs="/home/jiaoyanh/pseudonetcdf/Full_chemistry/201301/inputs"
outputs="/home/jiaoyanh/pseudonetcdf/Full_chemistry/201301/outputs"
infile1="fullchem.ts.$STDATE.bpch"
infile2="METBDY3D_CONUS_36_$STDATE"
infile3="METCRO3D_CONUS_36_$STDATE"


#echo $inputs
#echo $outputs
#echo $infile1
#echo $infile2
#echo $inflie3

#STDATE=$[$STDATE+1]
#cd $inputs

#mv AAA BBB
pncglobal2cmaq.py -f bpch $inputs/$infile1 --METBDY3D $inputs/$infile2 --METCRO3D $inputs/$infile3 --mapping=mappings.json  --outifolder=$outputs --outbfolder=$outputs

#mv dummyicon.nc $outputs/full_icon_$STDATE.nc
#mv dummybcon.nc $outputs/full_bcon_$STDATE.nc

cd /home/jiaoyanh/pseudonetcdf/Full_chemistry/201301/inputs
rm METBDY3D_CONUS_36_$STDATE
rm METCRO2D_CONUS_36_$STDATE
rm METCRO3D_CONUS_36_$STDATE
rm METDOT3D_CONUS_36_$STDATE
STDATE=$[$STDATE+1]
done_

and submit the code based on 

**Example:
    $ pncglobal2cmaq.py inputs/ts20120301.bpch --template=cb04tucl_ae6_aq > mappings.json
    $ pncglobal2cmaq.py inputs/ts20120301.bpch --METBDY3D inputs/METBDY3D_20120301 --METCRO3D inputs/METCRO3D_20120301 --mapping=mappings.json  --outifolder=outputs/ --outbfolder=outputs/**

the code run without any error message, but the output file with 
	TSTEP = UNLIMITED ; // (0 currently)
	DATE-TIME = 2 ;
	LAY = 34 ;
	PERIM = 524 ;

Do you have any idea where could be the potential error?

For the Hg part I am still testing, 

Thank you

**Comment by barronh** [comment]
I see you are making a template son as a part of the process. add a line between your pncglobal2cmaq.py commands that cat mappings.json. I don't think there is a cb05tucl_ae6_aq... So I don't know what would be in the mappings.json file...

**Comment by JiaoyanHuang** [comment]
It might be better to clarify this a bit more.

Example:
$ pncglobal2cmaq.py inputs/ts20120301.bpch --template=cb04tucl_ae6_aq > mappings.json
$ pncglobal2cmaq.py inputs/ts20120301.bpch --METBDY3D inputs/METBDY3D_20120301 --METCRO3D inputs/METCRO3D_20120301 --mapping=mappings.json --outifolder=outputs/ --outbfolder=outputs/

This example is copied from your pncglobal2cmaq.py so you can ignore all these.

I ran temple before ./run_pncgloabl2cmaq.sh, so there is a mappings.json, and here is the run_pncgloabl2cmaq.sh

#!/bin/bash

STDATE="20130101"
ENDATE="20130101"
#echo $STDATE
#echo $ENDATE

while [ $STDATE -le $ENDATE ]; do
cp -p /home/jiaoyanh/work/MCIP_data/36CONUS_12WUS_2013/mcip_d01/METBDY3D_CONUS_36_$STDATE.gz /home/jiaoyanh/pseudonetcdf/Full_chemistry/201301/inputs
cp -p /home/jiaoyanh/work/MCIP_data/36CONUS_12WUS_2013/mcip_d01/METCRO2D_CONUS_36_$STDATE.gz /home/jiaoyanh/pseudonetcdf/Full_chemistry/201301/inputs
cp -p /home/jiaoyanh/work/MCIP_data/36CONUS_12WUS_2013/mcip_d01/METCRO3D_CONUS_36_$STDATE.gz /home/jiaoyanh/pseudonetcdf/Full_chemistry/201301/inputs
cp -p /home/jiaoyanh/work/MCIP_data/36CONUS_12WUS_2013/mcip_d01/METDOT3D_CONUS_36_$STDATE.gz /home/jiaoyanh/pseudonetcdf/Full_chemistry/201301/inputs

cd /home/jiaoyanh/pseudonetcdf/Full_chemistry/201301/inputs
gunzip METBDY3D_CONUS_36_$STDATE.gz
gunzip METCRO2D_CONUS_36_$STDATE.gz
gunzip METCRO3D_CONUS_36_$STDATE.gz
gunzip METDOT3D_CONUS_36_$STDATE.gz

cd ../

inputs="/home/jiaoyanh/pseudonetcdf/Full_chemistry/201301/inputs"
outputs="/home/jiaoyanh/pseudonetcdf/Full_chemistry/201301/outputs"
infile1="fullchem.ts.$STDATE.bpch"
infile2="METBDY3D_CONUS_36_$STDATE"
infile3="METCRO3D_CONUS_36_$STDATE"

#echo $inputs
#echo $outputs
#echo $infile1
#echo $infile2
#echo $inflie3

#STDATE=$[$STDATE+1]
#cd $inputs

#mv AAA BBB
pncglobal2cmaq.py -f bpch $inputs/$infile1 --METBDY3D $inputs/$infile2 --METCRO3D $inputs/$infile3 --mapping=mappings.json --outifolder=$outputs --outbfolder=$outputs

#mv dummyicon.nc $outputs/full_icon_$STDATE.nc
#mv dummybcon.nc $outputs/full_bcon_$STDATE.nc

cd /home/jiaoyanh/pseudonetcdf/Full_chemistry/201301/inputs
rm METBDY3D_CONUS_36_$STDATE
rm METCRO2D_CONUS_36_$STDATE
rm METCRO3D_CONUS_36_$STDATE
rm METDOT3D_CONUS_36_$STDATE
STDATE=$[$STDATE+1]
done

What do you mean "add a line between your pncglobal2cmaq.py commands that cat mappings.json."?

Here is my mappings.json
https://gist.github.com/JiaoyanHuang/43cfd46635f5a26414c66a4e5533c361

Thank you

**Comment by barronh** [comment]
Thanks for posting the mappings.json and clarifying. By cat the mappings.json file, I wanted to see the results, which your gist post handles. I recommend that you add -x to the bash interpreter shebang.  That way you will see what actually gets called.

I am surprised that you don't get any error messages, since usually you get at least some warnings. The code also adds any errors to the output netcdf files as global attributes.  Have you tried looking there?

Try setting the --tstep=10000 option.

If that doesn't work, post a one value for each of your inputs and your output (even though it is empty) somewhere they can be downloaded. Also post which version of the code you are working with.

**Comment by JiaoyanHuang** [comment]
Dr. Barron, 

I am still having trouble using step and -x and here are all my files

https://drive.google.com/folderview?id=0B2fnN8rOK6WMNVA1WndHMVNrUnc&usp=sharing

**Comment by barronh** [comment]
Joey,

I've updated your mappings.json file (attached as mappings.txt) and I'm switching the way that the standard atmosphere variables get set. The other way would work if you fixed it, but I found it confusing -- see below. In the mappings.txt, I have also added STDTMP and STDPRES to the output for visualization. 

```
pncglobal2cmaq.py -f bpch,nogroup=True --expr="PSURF=np.ones_like(Hg0[:,0][:, None])*1013.25;TMPU=np.ones_like(Hg0[:])*np.array([287.7,286.9,286.0,285.2,284.3,283.4,282.6,281.7,280.7,279.8,278.9,277.9,276.8,275.3,273.6,271.8,270.0,268.2,265.8,262.8,259.7,256.4,252.9,249.2,245.2,241.0,236.4,230.5,223.6,216.8,216.6,216.6,216.6,216.6,216.6,216.6,216.6,217.5,219.8,222.0,225.3,233.6,250.5,269.2,260.0,237.7,214.3])[None,:47, None, None]" -v hyam,hybm,Hg2,Hg0,HgP fullchem.ts.20130101.bpch --METBDY3D METBDY3D_CONUS_36_20130101 --METCRO3D METCRO3D_CONUS_36_20130101 --mapping=mappings.json --outifolder=. --outbfolder=.
```

I have attached a image made from the results using the following command. Note that you need to verify the results before you use them.

```
pncboundaries.py -r TSTEP,mean -v HG,STDPRES fullchem.ts.20130101.bpch.BCON.nc test
```

[mappings.txt](https://github.com/barronh/pseudonetcdf/files/303524/mappings.txt)
![testhg](https://cloud.githubusercontent.com/assets/1191149/15874321/9b4e0b76-2cd0-11e6-8cad-274b76556a6f.png)

**Comment by JiaoyanHuang** [comment]
Dr. Barron, 

I still have some questions, you add 

--expr="PSURF=np.ones_like(Hg0[:,0][:, None])*1013.25;TMPU=np.ones_like(Hg0[:])*np.array([287.7,286.9,286.0,285.2,284.3,283.4,282.6,281.7,280.7,279.8,278.9,277.9,276.8,275.3,273.6,271.8,270.0,268.2,265.8,262.8,259.7,256.4,252.9,249.2,245.2,241.0,236.4,230.5,223.6,216.8,216.6,216.6,216.6,216.6,216.6,216.6,216.6,217.5,219.8,222.0,225.3,233.6,250.5,269.2,260.0,237.7,214.3])[None,:47, None, None]"

Can I just add this into mapping.jon and change AIRMOLDEN, AIRMASSDEN, and CMAQSPECIES to for_stdatm_use_as_expr?

If we want to add other species can I just add them to mapping.jon?

if I use --tstep==24, my output file will be generate with 24 tstep with same value? or it will vary based on the bpch hourly file?

Thank you for the help, this really solve my problem.

Joey

**Comment by barronh** [comment]
1) You can add definitions using the stdatm options, but I found that method less clear as I tried to revise it. I found it clearer to add the stdatm variables to the file via the --expr file so that the standard equations work.

2) Yes, you can add what ever translations you want.

3) The TSTEP variable will overwrite the determined time step. If you say it is 24h and your files are 1h, that will not be good.

**Comment by JiaoyanHuang** [comment]
Dr. Barron, 

Than you so much, it is working now. I will play around the code to output the full data that I want.

Joey
