### ISSUE TITLE
Converting CAMx NetCDF to NetCDF-CF format

### ISSUE THREAD

**Issue by miroi** [barronh/pseudonetcdf#96]
Dear  Barron,

I am trying to convert CAMx netCDF file to the netCDF-CF format for VAPOR visualizer.

Your Python pseudonetcdf file, together with CAMx nc (as input) files are here, 
https://drive.google.com/open?id=1Kff5cCdD0CvO3eQobNC7vvTZZZuXDmpz

I am getting this Python error (with numpy 1.18.2)
~~~
milias@194.160.44.72:~/work/open-collection/air-polution-modeling/CAMx/ubuntu-kch_194.160.44.72/test/.convert-pseudonetcdf.py
going to import PseudoNetCDF as pnc
going to open nc file ...
going to rename dimensions ...
going to create variable...
setting timev...
doing rawf.getTimes()...
Traceback (most recent call last):
  File "./convert-pseudonetcdf.py", line 37, in <module>
    print("rawf.getTimes()",rawf.getTimes()) ### gives error !
  File "/home/milias/.local/lib/python3.6/site-packages/PseudoNetCDF/core/_files.py", line 1727, in getTimes
    for yyyy, day in zip(yyyys, days)])
  File "/home/milias/.local/lib/python3.6/site-packages/PseudoNetCDF/core/_files.py", line 1727, in <listcomp>
    for yyyy, day in zip(yyyys, days)])
  File "/home/milias/.local/lib/python3.6/site-packages/numpy/ma/core.py", line 4344, in __int__
    raise MaskError('Cannot convert masked element to a Python int.')
numpy.ma.core.MaskError: Cannot convert masked element to a Python int.
milias@194.160.44.72:~/work/open-collection/air-polution-modeling/CAMx/ubuntu-kch_194.160.44.72/test/.
~~~

Any help, please ?

**Comment by barronh** [comment]
Your files seems corrupted or incomplete. I looked at both of these files. 

```
CAMx-netCDF-files/CAMx_test_run.avrg.grd01.nc  
CAMx-netCDF-files/testin.nc  
```

All the data after the 6th time steps are masked or missing. The `getTimes` function derives its values from `TFLAG`. Obviously, it cannot derive a valid time from a missing value. Below is a quick look at your `TFLAG` values. You can see that they are missing, and they are oddly spaced. The `TFLAG` has YYYYJJJ dates and HHMMSS times. Your dates look reasonable, but it seems weird for HHMMSS to be output at irregular intervals (0 - 150: 110 s; 150 - 300: 70s; 300 - 450: 110s; etc).

```
print(rawf.variables['TFLAG'])
rawf.variables['TFLAG'][:, 0]
```
```
<class 'netCDF4._netCDF4.Variable'>
int32 TFLAG(TSTEP, VAR, DATE-TIME)
    units: YYYYDDD,HHMMSS
    long_name: Start time flag
    var_desc: Timestep start date and time
unlimited dimensions: 
current shape = (16, 29, 2)
filling on, default _FillValue of -2147483647 used
masked_array(
  data=[[2002154, 0],
        [2002154, 150],
        [2002154, 300],
        [2002154, 450],
        [2002154, 600],
        [2002154, 750],
        [--, --],
        [--, --],
        [--, --],
        [--, --],
        [--, --],
        [--, --],
        [--, --],
        [--, --],
        [--, --],
        [--, --]],
  mask=[[False, False],
        [False, False],
        [False, False],
        [False, False],
        [False, False],
        [False, False],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]],
  fill_value=-2147483647,
  dtype=int32)
```

Before trying to use something like VAPOR, I'd suggest you review your data using more basic tools. ncdump would be a good start. A quick inspection with `ncdump CAMx-netCDF-files/CAMx_test_run.avrg.grd01.nc | less` or `ncdump CAMx-netCDF-files/testin.nc | less` would reveal missing data.

Then, if you felt good about your data, I'd suggest using a reader that has a longer history with CAMx (e.g., VERDI, Panoply, anything that supports the netcdf-java library).

You can force the conversion script to work for the first 6 times. If you really want to, replace

```
rawf = pnc.pncopen('CAMx-netCDF-files/testin.nc', format='ioapi').sliceDimensions(TSTEP=slice(None, 6))
```

with

```
rawf = pnc.pncopen('CAMx-netCDF-files/testin.nc', format='netcdf').sliceDimensions(TSTEP=slice(None, 6))
```

However, it seems there are bigger problems.

**Comment by miroi** [comment]
Many thanks ! The reason was that I set only 6 time steps, so I got poor nc file for the transformation. So I run the full simulation, and convert the nc file. Unfortunately, there was another error in VAPOR, so I decided to turn to VERDI and PANOPLY visualisations, which read camx netcdf outputs.
